server:
  port: 8090

logging:
  level:
    org.springframework: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  messages:
    basename: messages  
  security:
    user:
      name: minsong
      password: 1234
  datasource:    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    database-platform : org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true